name: Socket Vulnerability Scan

on:
  push:
    branches:
      - main

jobs:
  socket-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          pwd
          npm install -g socket
          cd ./scripts/socket-security
          pwd
          pip install .

      - name: Run Socket scan
        run: |
          # socket scan create --report --repo=${{github.event.repository.name}} --branch=${{github.ref_name}} ${{github.repository_owner}} .
          SCAN_OUTPUT=$(socket scan create --report --repo=${{github.event.repository.name}} --branch=${{github.ref_name}} ${{github.repository_owner}} .)
          SCAN_ID=$(echo "$SCAN_OUTPUT" | grep -o "scanId: '.*'" | awk -F"'" '{print $2}')
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
          echo "SCAN_ID: ${SCAN_ID}"
        env:
          SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_API_TOKEN }}

      - name: Show Report
        shell: bash
        run: |
          python scripts/socket-security/socket_security/fetch_report.py
        env:
          SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_API_TOKEN }}
          SLUG: ${{github.repository_owner}}
